### Variables
@URL = http://localhost:8888
@APIURL = {{URL}}/api/v1/products

### ping da API
GET {{URL}}/ping

### Get produto por ID não encontrado
GET {{APIURL}}/a1b2c3d4-e5f6-1234-5678-90abcdef1234
Accept: application/json

### Get produto por ID encontrado
GET {{APIURL}}/0d605862-91e8-11f0-9140-00155d6d572f
Accept: application/json

### Get traz produtos para fazer a comparação por list de IDs
GET {{APIURL}}/compare?ids=0d605862-91e8-11f0-9140-00155d6d572f,034aeff8-90ea-11f0-95f2-00155d6d5ec0,034afa35-90ea-11f0-95f2-00155d6d5ec0,034b11f9-90ea-11f0-95f2-00155d6d5ec0
Accept: application/json

### Get traz erro porque a lista de IDs é inválida
GET {{APIURL}}/compare?ids=id-invalido
Accept: application/json

### Get todos os produtos
GET {{APIURL}}/
Accept: application/json

### Get todos os produtos com paginação
GET {{APIURL}}?page=1&limit=2
Accept: application/json

### Adicionar um produto
POST {{APIURL}}/
Content-Type: application/json

{
    "nome": "produto 3",
    "url_imagem": "http://produto.com/imagem3.jpg",
    "descricao": "Produto 3",
    "preco": 4.90,
    "classificacao": "Eletrônicos",
    "especificacao": "Este produto possui as seguintes especificações técnicas: abc"
}

### Adicionar um produto
POST {{APIURL}}/
Content-Type: application/json

{
    "nome": "produto 2",
    "url_imagem": "http://produto.com/imagem2.jpg",
    "descricao": "Produto 2",
    "preco": 18.80,
    "classificacao": "Eletrônicos",
    "especificacao": "Este produto possui as seguintes especificações técnicas: xyz"
}

### Deleta um produto
DELETE {{APIURL}}/a1b2c3d4-e5f6-1234-5678-90abcdef1234
Content-Type: application/json

### Alterar um produto
PUT {{APIURL}}/0621c52e-91f4-11f0-abfa-00155d6d572f
Content-Type: application/json

{
    "id": "0621c52e-91f4-11f0-abfa-00155d6d572f",
    "nome": "produto 333",
    "url_imagem": "http://produto.com/imagem333.jpg",
    "descricao": "Produto 333",
    "preco": 18.80,
    "classificacao": "eletronicos",
    "especificacao": "abc32433244"
}